server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import:
      - optional:file:./env/db.env.properties
      - optional:file:./.env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 배포 전에 validate 또는 none 으로 변경
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET:}
  expiration-ms : ${JWT_EXPIRATION_MS}

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate가 실행하는 모든 SQL 쿼리를 보여줍니다.
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 쿼리의 파라미터 값까지 보여줍니다.
    org.springframework.orm.jpa: DEBUG # JPA 관련 상세 로그를 보여줍니다.